### ISSUE TITLE
 Refusing to install package with name "@waves/waves-api" under a package

### ISSUE THREAD

**Issue by lunchact** [wavesplatform/waves-api#78]
Need to change "name": "@waves/waves-api" to something else.

Example "name": "node-waves-api" in the package.json file.

**Comment by chelahmy** [comment]
@ is [npm-scope](https://docs.npmjs.com/misc/scope).

I have the same problem with my debian jessie since its latest npm does not support scoping. Mine also cannot install typescript. So I cannot install @waves/waves-api.

Removing @ is not straight forward because it is being referencing in many scripts. Anyway, scoping is the way forward.

**Comment by xenohunter** [comment]
Hello. Sorry, we cannot change it. Please, update you npm version. It can be done with `npm i -g npm`.
